#!/bin/bash
# Enhanced rearrangement generation pipeline with LLM diversification
# Generated by integrate_llm_diversification.py

set -e

# Configuration
OUTPUT_DIR="../custom_clevr/output"
SCENES_FILE="$OUTPUT_DIR/clevr_ref+_scenes.json"
REFEXPS_FILE="$OUTPUT_DIR/clevr_ref+_base_refexps.json"
BASE_REARRANGEMENTS_FILE="$OUTPUT_DIR/clevr_ref+_rearrangements.json"

echo "=== Enhanced Rearrangement Generation Pipeline ==="
echo "Starting at $(date)"

# Step 1: Generate base rearrangement expressions
echo "Step 1: Generating base rearrangement expressions..."
python generate_rearrangement_expressions.py \
    --input_refexps_file $REFEXPS_FILE \
    --input_scenes_file $SCENES_FILE \
    --output_rearrangement_file $BASE_REARRANGEMENTS_FILE \
    --num_refexps 100 \
    --rearrangements_per_refexp 1 \
    --verbose

echo "Generated $(python -c "import json; data=json.load(open('$BASE_REARRANGEMENTS_FILE')); print(len(data.get('expression_pairs', [])))" 2>/dev/null || echo "?") rearrangement pairs"


# Step 2: LLM Diversification
echo "Step 2: LLM Diversification of rearrangement expressions..."

# Diversify with openai gpt-3.5-turbo
echo "Diversifying with openai gpt-3.5-turbo..."
python llm_diversify_rearrangements.py \
    --rearrangements_file $BASE_REARRANGEMENTS_FILE \
    --scenes_file $SCENES_FILE \
    --output_file $OUTPUT_DIR/clevr_ref+_rearrangements_diversified_openai_gpt_3.5_turbo.json \
    --llm_provider openai \
    --model_name gpt-3.5-turbo \
    --api_key your-openai-api-key-here \
    --max_variations 2 \
    --temperature 0.8 \
    --max_pairs 50 \
    --delay 1.0

echo "Generated $(python -c "import json; data=json.load(open('$OUTPUT_DIR/clevr_ref+_rearrangements_diversified_openai_gpt_3.5_turbo.json')); print(len(data.get('expression_pairs', [])))" 2>/dev/null || echo "?") diversified pairs"


# Step 3: Finalization
echo "Step 3: Finalizing..."

echo "=== Pipeline completed at $(date) ==="
echo "Generated files:"
ls -la $OUTPUT_DIR/clevr_ref+_rearrangements*.json 2>/dev/null || echo "No files found"
